---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/labhexac/public_html/rescue/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/tar --exclude=".git" --exclude=".cpanel.yml" -cf - . | (cd $DEPLOYPATH && /bin/tar -xf -)
