<?php
require_once __DIR__.'/includes/layout.php';
$caseId=(int)($_GET['case']??0);$target=null;if($caseId){$s=db()->prepare('SELECT id,case_code,type,name,age,gender FROM cases WHERE id=? AND deleted_at IS NULL AND is_public=1');$s->execute([$caseId]);$target=$s->fetch();}
$success=null;$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();public_rate_limit();$caseId=(int)($_POST['target_case_id']??0);$target=null;if($caseId){$s=db()->prepare('SELECT id,case_code,type FROM cases WHERE id=? AND deleted_at IS NULL AND is_public=1');$s->execute([$caseId]);$target=$s->fetch();}
 $requester=trim((string)($_POST['requester_name']??''));$relation=trim((string)($_POST['relationship']??''));$phone=clean_phone((string)($_POST['requester_phone']??''));$missingName=trim((string)($_POST['missing_person_name']??''));
 if($requester==='')$errors[]='Your name is required.';if($relation==='')$errors[]='Relationship is required.';if(!valid_phone($phone))$errors[]='Valid phone is required.';if($missingName==='')$errors[]='Missing person name is required.';
 $verified=0;if(sms_configured()){if(!verify_phone_otp($phone,trim((string)($_POST['otp_code']??''))))$errors[]='Phone OTP is invalid or expired.';else $verified=1;}
 if(!$errors){try{$restrictedPhoto=!empty($_FILES['photo'])?save_restricted_photo($_FILES['photo'],'family'):null;$photo=$restrictedPhoto?['photo'=>$restrictedPhoto]:null;$code=family_request_code();$age=($_POST['missing_person_age']??'')!==''?(int)$_POST['missing_person_age']:null;$gender=$_POST['missing_person_gender']??'Unknown';if(!in_array($gender,['Male','Female','Other','Unknown'],true))$gender='Unknown';$stmt=db()->prepare('INSERT INTO family_match_requests(request_code,target_case_id,requester_name,relationship,requester_phone,requester_alt_phone,requester_district,requester_municipality,missing_person_name,missing_person_nickname,missing_person_age,missing_person_gender,missing_person_address,last_seen_date_bs,last_seen_location,clothing,distinguishing_marks,photo_url,phone_verified) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$code,$target['id']??null,$requester,$relation,$phone,clean_phone((string)($_POST['requester_alt_phone']??'')),trim((string)($_POST['requester_district']??'')),trim((string)($_POST['requester_municipality']??'')),$missingName,trim((string)($_POST['missing_person_nickname']??'')),$age,$gender,trim((string)($_POST['missing_person_address']??'')),trim((string)($_POST['last_seen_date_bs']??'')),trim((string)($_POST['last_seen_location']??'')),trim((string)($_POST['clothing']??'')),trim((string)($_POST['distinguishing_marks']??'')),$photo['photo']??null,$verified]);log_public_submission();$success=$code;}catch(Throwable $e){$errors[]='Could not submit request: '.$e->getMessage();}}
}
page_header('Family Match Request');
?>
<div class="section-title"><div><h1><?=render_lang('Family Match Request','परिवार मिलान अनुरोध')?></h1><div class="muted"><?=render_lang('Tell authorized staff why a rescued or recovered record may be your relative. Submitting this form does not itself confirm identity.','उद्धार वा बरामद रेकर्ड तपाईंको आफन्त हुन सक्ने कारण अधिकृत कर्मचारीलाई दिनुहोस्। यो फारमले आफैं पहिचान पुष्टि गर्दैन।')?></div></div></div>
<?php if($success):?><div class="card success-card"><h2><?=render_lang('Request submitted','अनुरोध दर्ता भयो')?></h2><p><?=render_lang('Save this Family Request ID:','यो परिवार अनुरोध आईडी सुरक्षित राख्नुहोस्:')?> <strong><?=e($success)?></strong></p><a class="btn btn-primary" href="<?=e(base_url('public_search.php'))?>">Back to Search</a></div><?php else:?>
<?php if($errors):?><div class="alert alert-danger"><ul><li><?=implode('</li><li>',array_map('e',$errors))?></li></ul></div><?php endif;?>
<?php if($target):?><div class="alert alert-info"><b><?=e($target['case_code'])?></b> · <?=e(case_type_label($target['type']))?></div><?php endif;?>
<form class="card form-card" method="post" enctype="multipart/form-data" id="familyForm"><?=csrf_field()?><input type="hidden" name="target_case_id" value="<?=e($target['id']??$caseId)?>">
<div class="grid"><div class="col-12 form-group-heading"><span class="group-number">1</span><div><b><?=render_lang('Your Details','तपाईंको विवरण')?></b></div></div>
<div class="col-4"><label><?=render_lang('Your Name *','तपाईंको नाम *')?><input name="requester_name" required></label></div><div class="col-4"><label><?=render_lang('Relationship *','सम्बन्ध *')?><input name="relationship" required placeholder="Father, mother, spouse, brother..."></label></div><div class="col-4"><label><?=render_lang('Phone *','फोन *')?><input name="requester_phone" id="requesterPhone" inputmode="tel" required></label></div>
<div class="col-4"><label><?=render_lang('Alternate Phone','वैकल्पिक फोन')?><input name="requester_alt_phone" inputmode="tel"></label></div><div class="col-4"><label><?=render_lang('District','जिल्ला')?><input name="requester_district"></label></div><div class="col-4"><label><?=render_lang('Municipality','पालिका')?><input name="requester_municipality"></label></div>
<?php if(sms_configured()):?><div class="col-12 otp-box"><button type="button" class="btn btn-secondary" id="sendOtp">Send Phone OTP / OTP पठाउनुहोस्</button><label>OTP *<input name="otp_code" maxlength="6" inputmode="numeric" required></label><span id="otpMsg" class="small muted"></span></div><?php else:?><div class="col-12 alert alert-warning small"><?=render_lang('SMS OTP gateway is not configured on this installation. The request will be marked Phone Unverified and staff must verify the number during review.','यस इन्स्टलेसनमा SMS OTP गेटवे सेट छैन। अनुरोध Phone Unverified का रूपमा जानेछ र कर्मचारीले समीक्षा गर्दा फोन पुष्टि गर्नुपर्छ।')?></div><?php endif;?>
<div class="col-12 form-group-heading"><span class="group-number">2</span><div><b><?=render_lang('Person You Are Looking For','तपाईंले खोजिरहनुभएको व्यक्ति')?></b></div></div>
<div class="col-6"><label><?=render_lang('Full Name *','पूरा नाम *')?><input name="missing_person_name" required></label></div><div class="col-3"><label><?=render_lang('Nickname','बोलाउने नाम')?><input name="missing_person_nickname"></label></div><div class="col-3"><label><?=render_lang('Age','उमेर')?><input type="number" name="missing_person_age" min="0" max="120"></label></div>
<div class="col-4"><label><?=render_lang('Gender','लिङ्ग')?><select name="missing_person_gender"><option value="Unknown">Unknown</option><option value="Male">Male / पुरुष</option><option value="Female">Female / महिला</option><option value="Other">Other / अन्य</option></select></label></div><div class="col-8"><label><?=render_lang('Home Address','घर ठेगाना')?><input name="missing_person_address"></label></div>
<div class="col-4"><label><?=render_lang('Last Seen Date BS','अन्तिम देखिएको मिति वि.सं.')?><input name="last_seen_date_bs" placeholder="2083-05-11"></label></div><div class="col-8"><label><?=render_lang('Last Seen Location','अन्तिम देखिएको स्थान')?><input name="last_seen_location"></label></div>
<div class="col-6"><label><?=render_lang('Clothing','लगाएको कपडा')?><textarea name="clothing"></textarea></label></div><div class="col-6"><label><?=render_lang('Unique Marks','विशेष चिन्ह')?><textarea name="distinguishing_marks" placeholder="Scar, tattoo, birthmark, surgery..."></textarea></label></div><div class="col-12"><label><?=render_lang('Recent Photo','हालसालैको फोटो')?><input type="file" name="photo" accept="image/jpeg,image/png,image/webp,image/*"></label></div></div>
<div class="form-actions"><button class="btn btn-primary btn-lg">Submit Match Request / मिलान अनुरोध पठाउनुहोस्</button></div></form>
<?php if(sms_configured()):?><script>document.getElementById('sendOtp')?.addEventListener('click',async()=>{const phone=document.getElementById('requesterPhone').value,msg=document.getElementById('otpMsg');msg.textContent='Sending...';const fd=new FormData();fd.append('csrf',<?=json_encode(csrf_token())?>);fd.append('phone',phone);const r=await fetch(<?=json_encode(base_url('otp.php'))?>,{method:'POST',body:fd});const j=await r.json();msg.textContent=j.message||j.error||'Done';});</script><?php endif;?>
<?php endif;?>
<?php page_footer(); ?>
