<?php
require_once __DIR__.'/../includes/layout.php'; require_once __DIR__.'/../includes/auth.php'; $admin=require_admin(['approver','superadmin']);
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$rid=(int)($_POST['request_id']??0);$decision=$_POST['decision']??'';$stmt=db()->prepare('SELECT * FROM close_approval_requests WHERE id=? AND status="pending"');$stmt->execute([$rid]);$r=$stmt->fetch();
 if($r){if($decision==='approve'){db()->beginTransaction();try{db()->prepare("UPDATE close_approval_requests SET status='approved',reviewed_by=?,reviewed_at=NOW(),review_notes=? WHERE id=?")->execute([$admin['id'],trim($_POST['notes']??''),$rid]);db()->prepare("UPDATE cases SET status='closed',close_reason=?,closed_at=NOW(),closed_by_admin_id=?,status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$r['reason'],$admin['id'],$admin['id'],$r['case_id']]);db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,note,public_visible) VALUES (?,?,'status','closed','Case formally closed.',1)")->execute([$r['case_id'],$admin['id']]);db()->commit();audit($admin['id'],'approve_close',(int)$r['case_id'],$r['reason']);flash('success','Case closed.');}catch(Throwable $e){db()->rollBack();flash('danger',$e->getMessage());}}
 else{db()->prepare("UPDATE close_approval_requests SET status='rejected',reviewed_by=?,reviewed_at=NOW(),review_notes=? WHERE id=?")->execute([$admin['id'],trim($_POST['notes']??''),$rid]);$cs=db()->prepare('SELECT status,current_condition FROM cases WHERE id=?');$cs->execute([$r['case_id']]);$cur=$cs->fetch();if($cur&&$cur['status']==='close_requested'){db()->prepare("UPDATE cases SET status='under_review',status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$admin['id'],$r['case_id']]);db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,condition_after,note,public_visible) VALUES (?,?,'status','under_review',?,'Case remains under review.',1)")->execute([$r['case_id'],$admin['id'],$cur['current_condition']?:'unknown']);}audit($admin['id'],'reject_close',(int)$r['case_id'],trim($_POST['notes']??''));flash('success','Close request rejected. Operational status remains active.');}}
 redirect(base_url('admin/approvals.php'));}
$rows=db()->query("SELECT r.*,c.case_code,c.name,a.name requested_by_name FROM close_approval_requests r JOIN cases c ON c.id=r.case_id JOIN admins a ON a.id=r.requested_by WHERE r.status='pending' ORDER BY r.requested_at")->fetchAll();page_header('Close Approvals',true);
?>
<div class="section-title"><h1>Close Approval Requests</h1><a class="btn btn-ghost" href="<?=e(base_url('admin/dashboard.php'))?>">Back</a></div>
<?php foreach($rows as $r):?><div class="card"><div class="section-title"><div><h2><?=e($r['case_code'])?> — <?=e($r['name'])?></h2><div class="muted">Requested by <?=e($r['requested_by_name'])?> · <?=e($r['requested_at'])?></div></div><a class="btn btn-secondary" href="<?=e(base_url('admin/case.php?id='.$r['case_id']))?>">View Case</a></div><div class="alert alert-warning"><b>Requested reason:</b><br><?=nl2br(e($r['reason']))?></div><form method="post"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><label>Review Notes<textarea name="notes"></textarea></label><div class="form-actions"><button class="btn btn-success" name="decision" value="approve">Approve & Close</button><button class="btn btn-danger" name="decision" value="reject">Reject</button></div></form></div><?php endforeach;?><?php if(!$rows):?><div class="card">No pending close approvals.</div><?php endif;?>
<?php page_footer(); ?>
