<?php
require_once __DIR__.'/../includes/layout.php';require_once __DIR__.'/../includes/auth.php';$admin=require_admin();$id=(int)($_GET['id']??0);$q=db()->prepare("SELECT c.*,d.body_id,d.current_mortuary,d.current_storage_location,d.body_bag_no,d.seal_no FROM cases c JOIN deceased_details d ON d.case_id=c.id WHERE c.id=? AND c.deleted_at IS NULL");$q->execute([$id]);$case=$q->fetch();if(!$case){http_response_code(404);exit('Deceased/DVI case not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'&&can_manage_dvi($admin['role'])){verify_csrf();$type=$_POST['event_type']??'other';$allowed=['recovered','bagged','sealed','received','transferred','pm_started','pm_completed','sample_collected','stored','other'];if(!in_array($type,$allowed,true))$type='other';$dt=trim((string)($_POST['event_datetime']??''));$dt=$dt!==''?str_replace('T',' ',$dt).(strlen($dt)<=16?':00':''):date('Y-m-d H:i:s');$to=trim((string)($_POST['to_location']??''));db()->prepare('INSERT INTO body_custody_events(case_id,event_type,event_datetime,event_date_bs,from_location,to_location,body_bag_no,seal_no,handled_by_name,handled_by_post,handled_by_office,admin_id,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$type,$dt,trim((string)($_POST['event_date_bs']??'')),trim((string)($_POST['from_location']??'')),$to,trim((string)($_POST['body_bag_no']??'')),trim((string)($_POST['seal_no']??'')),trim((string)($_POST['handled_by_name']??$admin['name'])),trim((string)($_POST['handled_by_post']??$admin['post_title'])),trim((string)($_POST['handled_by_office']??$admin['office_name'])),$admin['id'],trim((string)($_POST['notes']??''))]);if($to!=='')db()->prepare('UPDATE deceased_details SET current_storage_location=?,updated_at=NOW() WHERE case_id=?')->execute([$to,$id]);audit($admin['id'],'add_custody_event',$id,$type.' -> '.$to);flash('success','Chain-of-custody event recorded.');redirect(base_url('admin/custody.php?id='.$id));}
$e=db()->prepare('SELECT x.*,a.name admin_name FROM body_custody_events x LEFT JOIN admins a ON a.id=x.admin_id WHERE x.case_id=? ORDER BY x.event_datetime DESC,x.id DESC');$e->execute([$id]);$events=$e->fetchAll();page_header('Chain of Custody',true);
?>
<div class="section-title"><div><div class="card-kicker">DVI CHAIN OF CUSTODY</div><h1><?=e($case['body_id'])?></h1><div class="muted"><?=e($case['case_code'])?> · <?=e($case['current_mortuary'])?></div></div><a class="btn btn-ghost" href="<?=e(base_url('admin/case.php?id='.$id))?>">Back to Case</a></div>
<?php if(can_manage_dvi($admin['role'])):?><form method="post" class="card form-card"><?=csrf_field()?><div class="grid"><div class="col-3"><label>Event Type<select name="event_type"><?php foreach(['recovered','bagged','sealed','received','transferred','pm_started','pm_completed','sample_collected','stored','other'] as $t):?><option value="<?=$t?>"><?=e(ucwords(str_replace('_',' ',$t)))?></option><?php endforeach;?></select></label></div><div class="col-3"><label>Date/Time<input type="datetime-local" name="event_datetime"></label></div><div class="col-3"><label>BS Date<input name="event_date_bs" placeholder="2083-05-11"></label></div><div class="col-3"><label>Body Bag No.<input name="body_bag_no" value="<?=e($case['body_bag_no'])?>"></label></div><div class="col-3"><label>Seal No.<input name="seal_no" value="<?=e($case['seal_no'])?>"></label></div><div class="col-4"><label>From Location<input name="from_location"></label></div><div class="col-5"><label>To Location<input name="to_location"></label></div><div class="col-4"><label>Handled By<input name="handled_by_name" value="<?=e($admin['name'])?>"></label></div><div class="col-4"><label>Post<input name="handled_by_post" value="<?=e($admin['post_title'])?>"></label></div><div class="col-4"><label>Office<input name="handled_by_office" value="<?=e($admin['office_name'])?>"></label></div><div class="col-12"><label>Notes<textarea name="notes"></textarea></label></div></div><button class="btn btn-primary">Record Custody Event</button></form><?php endif;?>
<div class="card"><h2>Immutable Operational History</h2><div class="timeline"><?php foreach($events as $x):?><div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content"><div class="timeline-head"><b><?=e(ucwords(str_replace('_',' ',$x['event_type'])))?></b><time><?=e($x['event_datetime'])?></time></div><p><?=e($x['from_location'])?><?=($x['from_location']||$x['to_location'])?' → ':''?><?=e($x['to_location'])?></p><div class="small">Bag <?=e($x['body_bag_no'])?> · Seal <?=e($x['seal_no'])?> · <?=e($x['handled_by_name'])?> · <?=e($x['handled_by_office'])?></div><?php if($x['notes']):?><div class="timeline-note"><?=nl2br(e($x['notes']))?></div><?php endif;?></div></div><?php endforeach;?></div></div>
<?php page_footer(); ?>
