<?php
require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/SimpleXlsx.php'; $admin=require_admin();
$ids=[]; if(!empty($_GET['ids']))$ids=array_values(array_filter(array_map('intval',explode(',',$_GET['ids']))));
$where='c.deleted_at IS NULL';$args=[];if($ids){$where.=' AND c.id IN ('.implode(',',array_fill(0,count($ids),'?')).')';$args=$ids;}
$stmt=db()->prepare("SELECT c.*,r.latitude,r.longitude,r.address rescue_address,r.accuracy FROM cases c LEFT JOIN rescue_locations r ON r.id=(SELECT MAX(r2.id) FROM rescue_locations r2 WHERE r2.case_id=c.id) WHERE $where ORDER BY c.id DESC");$stmt->execute($args);$cases=$stmt->fetchAll();
$headers=['case_id','case_code','type','name','age','gender','from_location','missing_person_context','associated_place_name','purpose_en','purpose_np','vehicle_no','nationality_code','nationality_name','foreign_national_category','identity_document_type','identity_document_number','last_contacted_bs','last_contacted_time','last_seen_address','other_family_members_missing','photo_file_name','family_contact_name','family_contact_phone','total_persons','latitude','longitude','accuracy','status','current_condition','where_found','current_location','shifted_to','status_note','status_updated_at','rescue_description','additional_notes','created_at','updated_at'];$rows=[$headers];
foreach($cases as $c){$photo=$c['photo_url']?basename($c['photo_url']):'';$rows[]=[(int)$c['id'],$c['case_code'],$c['type'],$c['name'],$c['age'],$c['gender'],$c['from_location'],$c['missing_person_context'],$c['associated_place_name'],$c['purpose_en'],$c['purpose_np'],$c['vehicle_no'],$c['nationality_code'],$c['nationality_name'],$c['foreign_national_category'],$c['identity_document_type'],$c['identity_document_number'],$c['last_contacted_bs'],$c['last_contacted_time'],$c['last_seen_address'],(int)$c['other_family_members_missing'],$photo,$c['family_contact_name'],$c['family_contact_phone'],$c['total_persons'],$c['latitude'],$c['longitude'],$c['accuracy'],$c['status'],$c['current_condition'],$c['where_found'],$c['current_location'],$c['shifted_to'],$c['status_note'],$c['status_updated_at'],$c['rescue_description'],$c['additional_notes'],$c['created_at'],$c['updated_at']];}
$photos=[['case_code','photo_url','thumbnail_url']];foreach($cases as $c){$restricted=$c['type']==='deceased'&&!can_manage_dvi($admin['role']);$photos[]=[$c['case_code'],$restricted?'':$c['photo_url'],$restricted?'':$c['thumb_url']];}
$updateRows=[['case_code','updated_at','status','condition','where_found','current_location','shifted_to','note','public_visible','updated_by']];
$sheets=['Cases'=>$rows];
if($cases){
 $caseIds=array_column($cases,'id');$ph=implode(',',array_fill(0,count($caseIds),'?'));
 $u=db()->prepare("SELECT u.*,c.case_code,a.name admin_name FROM case_updates u JOIN cases c ON c.id=u.case_id LEFT JOIN admins a ON a.id=u.admin_id WHERE u.case_id IN ($ph) ORDER BY u.case_id,u.created_at,u.id");$u->execute($caseIds);foreach($u->fetchAll() as $x)$updateRows[]=[$x['case_code'],$x['created_at'],$x['status_after'],$x['condition_after'],$x['where_found'],$x['current_location'],$x['shifted_to'],$x['note'],(int)$x['public_visible'],$x['admin_name']];
 $rr=[['case_code','identity_status','nickname','estimated_age_min','estimated_age_max','permanent_address','person_phone','workplace','destination','emergency_contact_name','emergency_contact_phone','documents_found','identity_document_type','identity_document_number','rescue_datetime','rescue_date_bs','rescue_location','rescue_latitude','rescue_longitude','rescued_by','rescued_by_type','rescuing_institution','rescuing_institution_phone','condition_level','conscious','can_communicate','medical_attention','injury_summary','special_assistance','current_place_type','current_institution','current_institution_address','current_latitude','current_longitude','institution_contact_name','institution_contact_post','institution_contact_phone','institution_alt_phone','institution_office_phone','institution_email','language_spoken','height_cm','clothing','distinguishing_marks','belongings','reunification_status']];
 $st=db()->prepare("SELECT c.case_code,d.* FROM rescued_person_details d JOIN cases c ON c.id=d.case_id WHERE d.case_id IN ($ph) ORDER BY d.case_id");$st->execute($caseIds);foreach($st->fetchAll() as $x)$rr[]=[$x['case_code'],$x['identity_status'],$x['nickname'],$x['estimated_age_min'],$x['estimated_age_max'],$x['permanent_address'],$x['person_phone'],$x['workplace'],$x['destination'],$x['emergency_contact_name'],$x['emergency_contact_phone'],$x['documents_found'],$x['identity_document_type'],$x['identity_document_number'],$x['rescue_datetime_gregorian'],$x['rescue_date_bs'],$x['rescue_location'],$x['rescue_latitude'],$x['rescue_longitude'],$x['rescued_by_name'],$x['rescued_by_type'],$x['rescuing_institution_name'],$x['rescuing_institution_phone'],$x['condition_level'],$x['conscious'],$x['can_communicate'],$x['medical_attention'],$x['injury_summary'],$x['special_assistance'],$x['current_place_type'],$x['current_institution_name'],$x['current_institution_address'],$x['current_latitude'],$x['current_longitude'],$x['institution_contact_name'],$x['institution_contact_post'],$x['institution_contact_phone'],$x['institution_alt_phone'],$x['institution_office_phone'],$x['institution_email'],$x['language_spoken'],$x['height_cm'],$x['clothing'],$x['distinguishing_marks'],$x['belongings'],$x['reunification_status']];
 $sheets['RescuedPersons']=$rr;
 if(can_manage_dvi($admin['role'])){
   $dd=[['case_code','body_id','identity_status','suspected_name','estimated_age_min','estimated_age_max','height_cm','build','hair','facial_hair','clothing','footwear','jewellery','tattoos','scars','birthmarks','documents_found','devices_found','other_belongings','recovery_datetime','recovery_date_bs','recovery_location','recovery_latitude','recovery_longitude','river_waterbody','recovered_by','recovery_organization','police_office','recovery_officer','recovery_officer_post','recovery_officer_phone','body_bag_no','seal_no','current_mortuary','current_storage','fingerprint_collected','fingerprint_reference','fingerprint_result','dna_collected','dna_sample_id','dna_lab','dna_reference','dna_result','dental_summary','postmortem_reference','official_identification_method','official_identity_name','official_identity_age','official_identity_address','public_identity_release','identification_approved_at','body_condition','shifted_to_type','forensic_notes']];
   $st=db()->prepare("SELECT c.case_code,d.* FROM deceased_details d JOIN cases c ON c.id=d.case_id WHERE d.case_id IN ($ph) ORDER BY d.case_id");$st->execute($caseIds);foreach($st->fetchAll() as $x)$dd[]=[$x['case_code'],$x['body_id'],$x['identity_status'],$x['suspected_name'],$x['estimated_age_min'],$x['estimated_age_max'],$x['height_cm'],$x['build_description'],$x['hair_description'],$x['facial_hair_description'],$x['clothing'],$x['footwear'],$x['jewellery'],$x['tattoos'],$x['scars'],$x['birthmarks'],$x['documents_found'],$x['devices_found'],$x['other_belongings'],$x['recovery_datetime_gregorian'],$x['recovery_date_bs'],$x['recovery_location'],$x['recovery_latitude'],$x['recovery_longitude'],$x['river_waterbody'],$x['recovered_by_name'],$x['recovered_by_organization'],$x['police_office'],$x['recovery_officer_name'],$x['recovery_officer_post'],$x['recovery_officer_phone'],$x['body_bag_no'],$x['seal_no'],$x['current_mortuary'],$x['current_storage_location'],$x['fingerprint_collected'],$x['fingerprint_reference'],$x['fingerprint_result'],$x['dna_collected'],$x['dna_sample_id'],$x['dna_lab'],$x['dna_reference'],$x['dna_result'],$x['dental_summary'],$x['postmortem_reference'],$x['official_identification_method'],$x['official_identity_name'],$x['official_identity_age'],$x['official_identity_address'],$x['public_identity_release'],$x['identification_approved_at'],$x['body_condition'],$x['shifted_to_type'],$x['forensic_notes']];
   $sheets['DVI_Deceased']=$dd;
   $cust=[['case_code','event_type','event_datetime','event_date_bs','from_location','to_location','body_bag_no','seal_no','handled_by','post','office','linked_missing_case_id','linked_family_request_id','procedure_notes','close_after_handover','notes','created_at']];$st=db()->prepare("SELECT c.case_code,b.* FROM body_custody_events b JOIN cases c ON c.id=b.case_id WHERE b.case_id IN ($ph) ORDER BY b.case_id,b.event_datetime,b.id");$st->execute($caseIds);foreach($st->fetchAll() as $x)$cust[]=[$x['case_code'],$x['event_type'],$x['event_datetime'],$x['event_date_bs'],$x['from_location'],$x['to_location'],$x['body_bag_no'],$x['seal_no'],$x['handled_by_name'],$x['handled_by_post'],$x['handled_by_office'],$x['notes'],$x['created_at']];$sheets['DVI_Custody']=$cust;
 }
 $ho=[['case_code','handover_type','recipient_name','relationship','recipient_phone','recipient_address','recipient_id_type','recipient_id_number','handover_datetime','handover_location','witness_1','witness_2','handover_officer','officer_post','office','linked_missing_case_id','linked_family_request_id','procedure_notes','close_after_handover','notes','created_at']];$st=db()->prepare("SELECT c.case_code,h.* FROM handover_records h JOIN cases c ON c.id=h.case_id WHERE h.case_id IN ($ph) ORDER BY h.case_id,h.handover_datetime");$st->execute($caseIds);foreach($st->fetchAll() as $x)$ho[]=[$x['case_code'],$x['handover_type'],$x['recipient_name'],$x['relationship'],$x['recipient_phone'],$x['recipient_address'],$x['recipient_id_type'],$x['recipient_id_number'],$x['handover_datetime'],$x['handover_location'],$x['witness_1'],$x['witness_2'],$x['handover_officer_name'],$x['handover_officer_post'],$x['handover_office'],$x['linked_missing_case_id'],$x['linked_family_request_id'],$x['procedure_notes'],$x['close_after_handover'],$x['notes'],$x['created_at']];$sheets['Handovers']=$ho;
}
$sheets['CaseUpdates']=$updateRows;$sheets['Photos']=$photos;
if(can_manage_dvi($admin['role'])){$fm=[['request_code','target_case_code','requester_name','relationship','requester_phone','alt_phone','district','municipality','missing_person_name','nickname','age','gender','address','last_seen_bs','last_seen_location','clothing','distinguishing_marks','photo_url','phone_verified','status','review_notes','created_at']];$sql="SELECT f.*,c.case_code target_case_code FROM family_match_requests f LEFT JOIN cases c ON c.id=f.target_case_id";$fargs=[];if($ids){$sql.=" WHERE f.target_case_id IN (".implode(',',array_fill(0,count($ids),'?')).")";$fargs=$ids;}$sql.=' ORDER BY f.id DESC';$st=db()->prepare($sql);$st->execute($fargs);foreach($st->fetchAll() as $x)$fm[]=[$x['request_code'],$x['target_case_code'],$x['requester_name'],$x['relationship'],$x['requester_phone'],$x['requester_alt_phone'],$x['requester_district'],$x['requester_municipality'],$x['missing_person_name'],$x['missing_person_nickname'],$x['missing_person_age'],$x['missing_person_gender'],$x['missing_person_address'],$x['last_seen_date_bs'],$x['last_seen_location'],$x['clothing'],$x['distinguishing_marks'],$x['photo_url'],$x['phone_verified'],$x['status'],$x['review_notes'],$x['created_at']];$sheets['FamilyRequests']=$fm;}
$tmp=tempnam(sys_get_temp_dir(),'rescue_xlsx_').'.xlsx';SimpleXlsx::write($tmp,$sheets);audit($admin['id'],'export_xlsx',null,'Exported '.count($cases).' cases');header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="cases_export_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.filesize($tmp));readfile($tmp);unlink($tmp);exit;
