<?php
require_once __DIR__.'/../includes/layout.php';require_once __DIR__.'/../includes/auth.php';$admin=require_admin();
$statusNp=['submitted'=>'पेश गरिएको','under_review'=>'समीक्षामा','possible_match'=>'सम्भावित मिलान','verified'=>'प्रमाणित','rejected'=>'अस्वीकृत','closed'=>'बन्द'];
if($_SERVER['REQUEST_METHOD']==='POST'&&can_manage_dvi($admin['role'])){verify_csrf();$id=(int)($_POST['request_id']??0);$status=$_POST['status']??'under_review';if(!in_array($status,['submitted','under_review','possible_match','verified','rejected','closed'],true))$status='under_review';$phoneVerified=!empty($_POST['phone_verified'])?1:0;$notes=trim((string)($_POST['review_notes']??''));db()->prepare('UPDATE family_match_requests SET status=?,phone_verified=?,review_notes=?,reviewed_by=?,reviewed_at=NOW(),updated_at=NOW() WHERE id=?')->execute([$status,$phoneVerified,$notes,$admin['id'],$id]);audit($admin['id'],'review_family_match_request',null,'Request '.$id.' => '.$status);flash('success','Family match request updated.');redirect(base_url('admin/family_requests.php'));}
$statusFilter=$_GET['status']??'';$where='1=1';$args=[];if(in_array($statusFilter,['submitted','under_review','possible_match','verified','rejected','closed'],true)){$where='f.status=?';$args[]=$statusFilter;}$st=db()->prepare("SELECT f.*,c.case_code,c.type target_type,c.name target_name,a.name reviewer_name FROM family_match_requests f LEFT JOIN cases c ON c.id=f.target_case_id LEFT JOIN admins a ON a.id=f.reviewed_by WHERE $where ORDER BY f.created_at DESC LIMIT 300");$st->execute($args);$rows=$st->fetchAll();page_header('Family Match Requests',true);
?>
<div class="section-title"><div><div class="card-kicker">PUBLIC FAMILY INTAKE</div><h1><?=render_lang('Family Match Requests','परिवार मिलान अनुरोध')?></h1><div class="muted"><?=render_lang('Review public claims, verify the contact, and link only after appropriate identity checks.','सार्वजनिक दाबीहरू समीक्षा गर्नुहोस्, सम्पर्क प्रमाणित गर्नुहोस्, र उपयुक्त पहिचान जाँचपछि मात्र लिंक गर्नुहोस्।')?></div></div><a class="btn btn-ghost" href="<?=e(base_url('admin/dashboard.php'))?>"><?=render_lang('Back to Cases','केसमा फर्कनुहोस्')?></a></div>
<form class="card inline request-filter-bar" method="get"><label class="filter-label"><?=render_lang('Status','स्थिति')?><select name="status"><option value="">All statuses / सबै स्थिति</option><?php foreach(['submitted','under_review','possible_match','verified','rejected','closed'] as $s):?><option value="<?=e($s)?>" <?=$statusFilter===$s?'selected':''?>><?=e(ucwords(str_replace('_',' ',$s)))?> / <?=e($statusNp[$s])?></option><?php endforeach;?></select></label><button class="btn btn-secondary"><?=render_lang('Filter','फिल्टर')?></button></form>
<?php foreach($rows as $r):?><article class="card family-review-card"><div class="section-title compact-title"><div><h2><?=e($r['request_code'])?> · <?=e($r['missing_person_name'])?></h2><div class="muted small"><?=render_lang('Submitted','पेश गरिएको')?> <?=e($r['created_at'])?> · <?=render_lang(ucwords(str_replace('_',' ',$r['status'])),$statusNp[$r['status']]??$r['status'])?></div></div><?php if($r['case_code']):?><a class="btn btn-secondary" href="<?=e(base_url('admin/reconciliation.php?id='.$r['target_case_id']))?>"><?=e($r['case_code'])?> · <?=render_lang('Reconciliation','मिलान समीक्षा')?></a><?php endif;?></div>
<div class="family-request-meta">
<div><span><?=render_lang('Requester','अनुरोधकर्ता')?></span><b><?=e($r['requester_name'])?></b><small><?=e($r['relationship'])?></small><small><?=e($r['requester_phone'])?> <?=!empty($r['phone_verified'])?'<span class="status status-rescued_safe">'.render_lang('Verified','प्रमाणित').'</span>':'<span class="status">'.render_lang('Unverified','अप्रमाणित').'</span>'?></small></div>
<div><span><?=render_lang('Missing Person Details','हराइरहेको व्यक्तिको विवरण')?></span><b><?=render_lang('Age','उमेर')?> <?=e($r['missing_person_age']??'Unknown')?> · <?=e($r['missing_person_gender'])?></b><small><?=e($r['missing_person_address'])?></small><small><?=e($r['last_seen_location'])?> <?=e($r['last_seen_date_bs'])?></small></div>
<div><span><?=render_lang('Target Record','लक्षित रेकर्ड')?></span><b><?=$r['case_code']?e($r['case_code']):render_lang('No specific target','लक्षित रेकर्ड छैन')?></b><?php if(!empty($r['target_type'])):?><small><?=render_lang(case_type_label($r['target_type']),case_type_label($r['target_type'],'np'))?></small><?php endif;?></div>
</div>
<div class="family-request-meta family-request-meta-2col">
<div><span><?=render_lang('Clothing','लुगा')?></span><p><?=$r['clothing']?nl2br(e($r['clothing'])):'—'?></p></div>
<div><span><?=render_lang('Distinguishing Marks','पहिचान चिन्ह')?></span><p><?=$r['distinguishing_marks']?nl2br(e($r['distinguishing_marks'])):'—'?></p><?php if($r['photo_url']):?><a class="btn btn-sm btn-secondary" target="_blank" href="<?=e(base_url('admin/media/family/'.$r['id']))?>"><?=render_lang('View Restricted Family Photo','सीमित पारिवारिक फोटो हेर्नुहोस्')?></a><?php endif;?></div>
</div>
<?php if(can_manage_dvi($admin['role'])):?><form method="post" class="family-review-form"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><div class="grid"><div class="col-3"><label><?=render_lang('Status','स्थिति')?><select name="status"><?php foreach(['submitted','under_review','possible_match','verified','rejected','closed'] as $s):?><option value="<?=$s?>" <?=$r['status']===$s?'selected':''?>><?=e(ucwords(str_replace('_',' ',$s)))?> / <?=e($statusNp[$s])?></option><?php endforeach;?></select></label></div><div class="col-3"><label class="check-label"><input type="checkbox" name="phone_verified" value="1" <?=!empty($r['phone_verified'])?'checked':''?>><span><?=render_lang('Phone verified','फोन प्रमाणित')?></span></label></div><div class="col-6"><label><?=render_lang('Review Notes','समीक्षा टिप्पणी')?><textarea name="review_notes"><?=e($r['review_notes'])?></textarea></label></div></div><button class="btn btn-primary"><?=render_lang('Save Review','समीक्षा सुरक्षित गर्नुहोस्')?></button></form><?php endif;?></article><?php endforeach;?><?php if(!$rows):?><div class="card"><p><?=render_lang('No family match requests found.','कुनै परिवार मिलान अनुरोध फेला परेन।')?></p></div><?php endif;?>
<?php page_footer(); ?>
