<?php
require_once __DIR__.'/../includes/layout.php';require_once __DIR__.'/../includes/auth.php';$admin=require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'&&can_manage_dvi($admin['role'])){verify_csrf();$id=(int)($_POST['request_id']??0);$status=$_POST['status']??'under_review';if(!in_array($status,['submitted','under_review','possible_match','verified','rejected','closed'],true))$status='under_review';$phoneVerified=!empty($_POST['phone_verified'])?1:0;$notes=trim((string)($_POST['review_notes']??''));db()->prepare('UPDATE family_match_requests SET status=?,phone_verified=?,review_notes=?,reviewed_by=?,reviewed_at=NOW(),updated_at=NOW() WHERE id=?')->execute([$status,$phoneVerified,$notes,$admin['id'],$id]);audit($admin['id'],'review_family_match_request',null,'Request '.$id.' => '.$status);flash('success','Family match request updated.');redirect(base_url('admin/family_requests.php'));}
$statusFilter=$_GET['status']??'';$where='1=1';$args=[];if(in_array($statusFilter,['submitted','under_review','possible_match','verified','rejected','closed'],true)){$where='f.status=?';$args[]=$statusFilter;}$st=db()->prepare("SELECT f.*,c.case_code,c.type target_type,c.name target_name,a.name reviewer_name FROM family_match_requests f LEFT JOIN cases c ON c.id=f.target_case_id LEFT JOIN admins a ON a.id=f.reviewed_by WHERE $where ORDER BY f.created_at DESC LIMIT 300");$st->execute($args);$rows=$st->fetchAll();page_header('Family Match Requests',true);
?>
<div class="section-title"><div><div class="card-kicker">PUBLIC FAMILY INTAKE</div><h1>Family Match Requests / परिवार मिलान अनुरोध</h1><div class="muted">Review public claims, verify the contact, and link only after appropriate identity checks.</div></div><a class="btn btn-ghost" href="<?=e(base_url('admin/dashboard.php'))?>">Back to Cases</a></div>
<form class="inline filter-bar" method="get"><select name="status"><option value="">All statuses</option><?php foreach(['submitted','under_review','possible_match','verified','rejected','closed'] as $s):?><option value="<?=e($s)?>" <?=$statusFilter===$s?'selected':''?>><?=e(ucwords(str_replace('_',' ',$s)))?></option><?php endforeach;?></select><button class="btn btn-secondary">Filter</button></form>
<?php foreach($rows as $r):?><article class="card family-review-card"><div class="section-title compact-title"><div><h2><?=e($r['request_code'])?> · <?=e($r['missing_person_name'])?></h2><div class="muted small">Submitted <?=e($r['created_at'])?> · <?=e($r['status'])?></div></div><?php if($r['case_code']):?><a class="btn btn-secondary" href="<?=e(base_url('admin/reconciliation.php?id='.$r['target_case_id']))?>"><?=e($r['case_code'])?> · Reconciliation</a><?php endif;?></div>
<div class="grid"><div class="col-4"><b>Requester</b><p><?=e($r['requester_name'])?><br><?=e($r['relationship'])?><br><?=e($r['requester_phone'])?> <?=!empty($r['phone_verified'])?'<span class="status status-rescued_safe">Verified</span>':'<span class="status">Unverified</span>'?></p></div><div class="col-4"><b>Person Details</b><p>Age <?=e($r['missing_person_age']??'Unknown')?> · <?=e($r['missing_person_gender'])?><br><?=e($r['missing_person_address'])?><br><?=e($r['last_seen_location'])?> <?=e($r['last_seen_date_bs'])?></p></div><div class="col-4"><b>Target Record</b><p><?=e($r['case_code']?:'No specific target')?><?=!empty($r['target_type'])?'<br>'.e(case_type_label($r['target_type'])):''?></p></div><div class="col-6"><b>Clothing</b><p><?=nl2br(e($r['clothing']))?></p></div><div class="col-6"><b>Distinguishing Marks</b><p><?=nl2br(e($r['distinguishing_marks']))?></p><?php if($r['photo_url']):?><a class="btn btn-sm btn-secondary" target="_blank" href="<?=e(base_url('admin/media/family/'.$r['id']))?>">View Restricted Family Photo</a><?php endif;?></div></div>
<?php if(can_manage_dvi($admin['role'])):?><form method="post" class="family-review-form"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><div class="grid"><div class="col-3"><label>Status<select name="status"><?php foreach(['submitted','under_review','possible_match','verified','rejected','closed'] as $s):?><option value="<?=$s?>" <?=$r['status']===$s?'selected':''?>><?=e(ucwords(str_replace('_',' ',$s)))?></option><?php endforeach;?></select></label></div><div class="col-3"><label class="check-label"><input type="checkbox" name="phone_verified" value="1" <?=!empty($r['phone_verified'])?'checked':''?>><span>Phone verified</span></label></div><div class="col-6"><label>Review Notes<textarea name="review_notes"><?=e($r['review_notes'])?></textarea></label></div></div><button class="btn btn-primary">Save Review</button></form><?php endif;?></article><?php endforeach;?><?php if(!$rows):?><div class="card"><p>No family match requests found.</p></div><?php endif;?>
<?php page_footer(); ?>
