<?php
require_once __DIR__.'/../includes/layout.php';
require_once __DIR__.'/../includes/auth.php';
$admin=require_admin();$id=(int)($_GET['id']??0);
$q=db()->prepare('SELECT c.*,d.identity_status deceased_identity,d.body_id,d.official_identity_name,r.reunification_status FROM cases c LEFT JOIN deceased_details d ON d.case_id=c.id LEFT JOIN rescued_person_details r ON r.case_id=c.id WHERE c.id=? AND c.deleted_at IS NULL');$q->execute([$id]);$case=$q->fetch();
if(!$case||!in_array($case['type'],['rescued','deceased'],true)){http_response_code(404);exit('Handover is available for rescued/deceased cases.');}
$alreadyHanded=in_array($case['status'],['reunited','handed_over','closed'],true)||($case['type']==='deceased'&&($case['deceased_identity']??'')==='handed_over')||($case['type']==='rescued'&&($case['reunification_status']??'')==='reunited');
$eligible=!$alreadyHanded && ($case['type']==='rescued'||(in_array($case['deceased_identity']??'', ['confirmed','ready_handover'],true)&&can_approve_identification($admin['role'])));

$ms=db()->prepare("SELECT cm.candidate_case_id,cm.match_score,cm.status,m.case_code,m.name,m.age,m.from_location FROM case_matches cm JOIN cases m ON m.id=cm.candidate_case_id WHERE cm.source_case_id=? AND m.type='missing' AND m.deleted_at IS NULL AND cm.status<>'rejected' ORDER BY (cm.status='confirmed') DESC,cm.match_score DESC");$ms->execute([$id]);$missingCandidates=$ms->fetchAll();
$fr=db()->prepare("SELECT id,request_code,requester_name,relationship,requester_phone,missing_person_name,status FROM family_match_requests WHERE target_case_id=? ORDER BY (status='verified') DESC,id DESC");$fr->execute([$id]);$familyRequests=$fr->fetchAll();
$approvedMissingId=null;if($case['type']==='deceased'){$a=db()->prepare("SELECT proposed_missing_case_id FROM identification_approval_requests WHERE case_id=? AND status='approved' ORDER BY reviewed_at DESC,id DESC LIMIT 1");$a->execute([$id]);$approvedMissingId=$a->fetchColumn()?:null;if($approvedMissingId){$present=false;foreach($missingCandidates as $mc){if((int)$mc['candidate_case_id']===(int)$approvedMissingId){$present=true;break;}}if(!$present){$am=db()->prepare("SELECT id candidate_case_id,100.00 match_score,'confirmed' status,case_code,name,age,from_location FROM cases WHERE id=? AND type='missing' AND deleted_at IS NULL");$am->execute([(int)$approvedMissingId]);if($row=$am->fetch())array_unshift($missingCandidates,$row);}}}

function resolve_linked_missing(int $caseId): ?array {if(!$caseId)return null;$s=db()->prepare("SELECT id,case_code,name,status FROM cases WHERE id=? AND type='missing' AND deleted_at IS NULL");$s->execute([$caseId]);return $s->fetch()?:null;}
function request_or_close_resolved_missing(array $admin,array $missing,string $reason): void {
    if($missing['status']==='closed')return;
    if(can_close($admin['role'])){
        db()->prepare("UPDATE cases SET status='closed',close_reason=?,closed_at=NOW(),closed_by_admin_id=?,status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$reason,$admin['id'],$admin['id'],$missing['id']]);
        db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,note,public_visible) VALUES (?,?,'status','closed',?,1)")->execute([$missing['id'],$admin['id'],$reason]);
    }else{
        $x=db()->prepare("SELECT COUNT(*) FROM close_approval_requests WHERE case_id=? AND status='pending'");$x->execute([$missing['id']]);if(!(int)$x->fetchColumn())db()->prepare('INSERT INTO close_approval_requests(case_id,requested_by,reason) VALUES (?,?,?)')->execute([$missing['id'],$admin['id'],$reason]);
    }
}

if($_SERVER['REQUEST_METHOD']==='POST'&&can_manage_dvi($admin['role'])){
 verify_csrf();
 if(!$eligible){flash('danger',$alreadyHanded?'Final handover/reunification is already recorded.':'Deceased handover requires confirmed identity and an Approver/Superadmin.');redirect(base_url('admin/handover.php?id='.$id));}
 $recipient=trim((string)($_POST['recipient_name']??''));$relation=trim((string)($_POST['relationship']??''));$phone=clean_phone((string)($_POST['recipient_phone']??''));$loc=trim((string)($_POST['handover_location']??''));$officer=trim((string)($_POST['handover_officer_name']??''));
 $linkedMissingId=(int)($_POST['linked_missing_case_id']??0);$linkedMissingCode=trim((string)($_POST['linked_missing_case_code']??''));if(!$linkedMissingId&&$linkedMissingCode!==''){$ms=db()->prepare("SELECT id FROM cases WHERE case_code=? AND type='missing' AND deleted_at IS NULL");$ms->execute([$linkedMissingCode]);$linkedMissingId=(int)($ms->fetchColumn()?:0);if(!$linkedMissingId){flash('danger','Missing Case ID not found.');redirect(base_url('admin/handover.php?id='.$id));}}$linkedFamilyId=(int)($_POST['linked_family_request_id']??0);$procedure=trim((string)($_POST['procedure_notes']??''));$closeAfter=!empty($_POST['close_after_handover']);
 if($recipient===''||$relation===''||!valid_phone($phone)||$loc===''||$officer===''){flash('danger','Recipient, relationship, valid phone, handover location and officer are required.');redirect(base_url('admin/handover.php?id='.$id));}
 $linkedMissing=resolve_linked_missing($linkedMissingId);if($linkedMissingId&&!$linkedMissing){flash('danger','Selected Missing Case ID is invalid.');redirect(base_url('admin/handover.php?id='.$id));}
 if($case['type']==='deceased'&&$approvedMissingId&&$linkedMissingId&&(int)$approvedMissingId!==$linkedMissingId){flash('danger','Dead-body handover must use the Missing Case ID approved during formal identification.');redirect(base_url('admin/handover.php?id='.$id));}
 if($linkedFamilyId){$x=db()->prepare('SELECT id FROM family_match_requests WHERE id=? AND target_case_id=?');$x->execute([$linkedFamilyId,$id]);if(!$x->fetchColumn()){flash('danger','Selected Family Match Request is invalid.');redirect(base_url('admin/handover.php?id='.$id));}}
 $dt=trim((string)($_POST['handover_datetime']??''));$dt=$dt!==''?str_replace('T',' ',$dt).(strlen($dt)<=16?':00':''):date('Y-m-d H:i:s');$type=$case['type']==='rescued'?'rescued_reunification':'deceased_handover';
 db()->beginTransaction();try{
   db()->prepare('INSERT INTO handover_records(case_id,handover_type,recipient_name,relationship,recipient_phone,recipient_address,recipient_id_type,recipient_id_number,handover_datetime,handover_location,witness_1,witness_2,handover_officer_name,handover_officer_post,handover_office,approved_by,admin_id,linked_missing_case_id,linked_family_request_id,procedure_notes,close_after_handover,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$type,$recipient,$relation,$phone,trim((string)($_POST['recipient_address']??'')),trim((string)($_POST['recipient_id_type']??'')),trim((string)($_POST['recipient_id_number']??'')),$dt,$loc,trim((string)($_POST['witness_1']??'')),trim((string)($_POST['witness_2']??'')),$officer,trim((string)($_POST['handover_officer_post']??'')),trim((string)($_POST['handover_office']??'')),can_approve_identification($admin['role'])?$admin['id']:null,$admin['id'],$linkedMissingId?:null,$linkedFamilyId?:null,$procedure,$closeAfter?1:0,trim((string)($_POST['notes']??''))]);
   $finalStatus=$case['type']==='rescued'?'reunited':'handed_over';
   db()->prepare('UPDATE cases SET status=?,status_updated_at=NOW(),status_updated_by=?,current_location=?,updated_at=NOW() WHERE id=?')->execute([$finalStatus,$admin['id'],$loc,$id]);
   if($case['type']==='rescued')db()->prepare("UPDATE rescued_person_details SET reunification_status='reunited',reunited_at=?,updated_at=NOW() WHERE case_id=?")->execute([$dt,$id]);else db()->prepare("UPDATE deceased_details SET identity_status='handed_over',updated_at=NOW() WHERE case_id=?")->execute([$id]);
   if($linkedMissingId&&$case['type']==='rescued')db()->prepare("UPDATE case_matches SET status='confirmed',reviewed_by=?,reviewed_at=NOW() WHERE source_case_id=? AND candidate_case_id=?")->execute([$admin['id'],$id,$linkedMissingId]);
   if($linkedFamilyId)db()->prepare("UPDATE family_match_requests SET status='verified',reviewed_by=?,reviewed_at=NOW(),review_notes=CONCAT(COALESCE(review_notes,''),?) WHERE id=?")->execute([$admin['id'],"\nResolved through handover/reunification on ".$dt,$linkedFamilyId]);
   db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,condition_after,current_location,note,public_visible) VALUES (?,?,'transfer',?,?,?, ?,1)")->execute([$id,$admin['id'],$finalStatus,$case['type']==='deceased'?'deceased':'safe',$loc,'Family handover/reunification completed.'.($linkedMissing?' Linked missing case: '.$linkedMissing['case_code']:($linkedFamilyId?' Linked family request.':' Direct family verification.'))]);
   if($case['type']==='deceased')db()->prepare("INSERT INTO body_custody_events(case_id,event_type,event_datetime,to_location,handled_by_name,handled_by_post,handled_by_office,admin_id,notes) VALUES (?,'released',?,?,?,?,?,?,?)")->execute([$id,$dt,$loc,$officer,trim((string)($_POST['handover_officer_post']??'')),trim((string)($_POST['handover_office']??'')),$admin['id'],'Released to family/authorized recipient. '.$procedure]);
   if($closeAfter){
      $reason=($case['type']==='rescued'?'Rescued person reunited with family.':'Identified deceased handed over to family.').' Handover record completed.';
      if(can_close($admin['role'])){db()->prepare("UPDATE cases SET status='closed',close_reason=?,closed_at=NOW(),closed_by_admin_id=?,status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$reason,$admin['id'],$admin['id'],$id]);db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,note,public_visible) VALUES (?,?,'status','closed',?,1)")->execute([$id,$admin['id'],$reason]);}
      else{$x=db()->prepare("SELECT COUNT(*) FROM close_approval_requests WHERE case_id=? AND status='pending'");$x->execute([$id]);if(!(int)$x->fetchColumn())db()->prepare('INSERT INTO close_approval_requests(case_id,requested_by,reason) VALUES (?,?,?)')->execute([$id,$admin['id'],$reason]);}
      if($linkedMissing)request_or_close_resolved_missing($admin,$linkedMissing,'Resolved by link to '.$case['case_code'].' after family '.($case['type']==='rescued'?'reunification':'handover').'.');
   }
   db()->commit();audit($admin['id'],'family_handover',$id,$recipient.' · '.$relation.($linkedMissing?' · '.$linkedMissing['case_code']:''));flash('success',$closeAfter?(can_close($admin['role'])?'Handover completed and resolved case(s) closed.':'Handover completed. Closure approval was requested where required.'):'Handover/reunification recorded.');redirect(base_url('admin/handover.php?id='.$id));
 }catch(Throwable $e){db()->rollBack();flash('danger',$e->getMessage());redirect(base_url('admin/handover.php?id='.$id));}
}
$h=db()->prepare('SELECT h.*,a.name admin_name,m.case_code linked_missing_code,f.request_code family_request_code FROM handover_records h LEFT JOIN admins a ON a.id=h.admin_id LEFT JOIN cases m ON m.id=h.linked_missing_case_id LEFT JOIN family_match_requests f ON f.id=h.linked_family_request_id WHERE h.case_id=? ORDER BY h.handover_datetime DESC');$h->execute([$id]);$records=$h->fetchAll();
page_header('Handover / Tracing',true);
?>
<div class="section-title"><div><div class="card-kicker">TRACING → FAMILY HANDOVER → CLOSURE</div><h1><?=e($case['case_code'])?> · <?=e($case['type']==='deceased'?($case['body_id']?:'Dead Body'):'Rescued Person')?></h1><div class="muted"><?=e($case['name'])?></div></div><a class="btn btn-ghost" href="<?=e(base_url('admin/case.php?id='.$id))?>">Back to Case</a></div>
<?php if(!$eligible):?><div class="alert alert-danger"><b>Handover unavailable.</b> <?=e($alreadyHanded?'A final handover/reunification is already recorded.':($case['type']==='deceased'?'Confirmed identity plus Approver/Superadmin authorization is required.':'This case is not eligible for final reunification.'))?></div><?php endif;?>
<?php if($eligible&&can_manage_dvi($admin['role'])):?><form method="post" class="card form-card practical-form"><?=csrf_field()?>
<div class="grid">
<div class="col-12 form-group-heading"><span class="group-number">1</span><div><b>Trace Link / ट्रेस लिंक</b><div class="hint">Link to a Missing Case ID when one exists. If no missing case was filed, link a Family Match Request or use direct family verification.</div></div></div>
<div class="col-6"><label>Linked Missing Case ID<select name="linked_missing_case_id"><option value="">No missing case / दर्ता भएको Missing Case छैन</option><?php foreach($missingCandidates as $m):?><option value="<?=$m['candidate_case_id']?>" <?=((int)$approvedMissingId===(int)$m['candidate_case_id'])?'selected':''?>><?=e($m['case_code'].' · '.$m['name'].' · '.$m['match_score'].'%'.($m['status']==='confirmed'?' · confirmed':''))?></option><?php endforeach;?></select></label><label style="margin-top:10px">Or Enter Missing Case ID<input name="linked_missing_case_code" placeholder="Example: RN-..."><span class="hint">Use this when the missing case exists but is not in the suggested match list.</span></label></div>
<div class="col-6"><label>Linked Family Match Request<select name="linked_family_request_id"><option value="">Direct family verification / कुनै अनुरोध लिंक छैन</option><?php foreach($familyRequests as $f):?><option value="<?=$f['id']?>"><?=e($f['request_code'].' · '.$f['requester_name'].' · '.$f['relationship'].' · '.$f['missing_person_name'])?></option><?php endforeach;?></select></label></div>
<div class="col-12"><label>Other Procedure / Verification Performed<textarea name="procedure_notes" placeholder="Example: Family verified clothing/documents; police verification completed; hospital release procedure; witness verification..."></textarea></label></div>

<div class="col-12 form-group-heading"><span class="group-number">2</span><div><b>Family / Recipient Details / परिवार वा बुझ्ने व्यक्तिको विवरण</b></div></div>
<div class="col-4"><label>Recipient Name *<input name="recipient_name" required></label></div><div class="col-4"><label>Relationship *<input name="relationship" required placeholder="Father, mother, spouse, sibling..."></label></div><div class="col-4"><label>Recipient Phone *<input name="recipient_phone" required inputmode="tel"></label></div>
<div class="col-6"><label>Recipient Address<input name="recipient_address"></label></div><div class="col-3"><label>ID Type<input name="recipient_id_type" placeholder="Citizenship, passport..."></label></div><div class="col-3"><label>ID Number<input name="recipient_id_number"></label></div>
<div class="col-4"><label>Handover Date/Time<input type="datetime-local" name="handover_datetime"></label></div><div class="col-8"><label>Handover / Reunification Location *<input name="handover_location" required></label></div>
<div class="col-6"><label>Witness 1<input name="witness_1"></label></div><div class="col-6"><label>Witness 2<input name="witness_2"></label></div>

<div class="col-12 form-group-heading"><span class="group-number">3</span><div><b>Responsible Officer / जिम्मेवार अधिकारी</b></div></div>
<div class="col-4"><label>Officer *<input name="handover_officer_name" value="<?=e($admin['name'])?>" required></label></div><div class="col-4"><label>Post<input name="handover_officer_post" value="<?=e($admin['post_title'])?>"></label></div><div class="col-4"><label>Office<input name="handover_office" value="<?=e($admin['office_name'])?>"></label></div>
<div class="col-12"><label>Notes<textarea name="notes"></textarea></label></div>
<div class="col-12"><label class="check-label"><input type="checkbox" name="close_after_handover" value="1" checked><span><b>Close resolved case after handover / हस्तान्तरणपछि केस बन्द गर्नुहोस्</b><small><?=can_close($admin['role'])?'This user can close the case immediately.':'Your role will submit the required closure approval request automatically.'?></small></span></label></div>
</div>
<button class="btn btn-primary btn-lg" data-confirm="Complete final family handover/reunification and process closure?">Complete Handover / Reunification</button></form><?php endif;?>
<div class="card"><h2>Handover / Reunification History</h2><?php foreach($records as $r):?><div class="handover-row"><b><?=e($r['handover_type'])?> · <?=e($r['handover_datetime'])?></b><p><?=e($r['recipient_name'])?> (<?=e($r['relationship'])?>) · <?=e($r['recipient_phone'])?><br><?=e($r['handover_location'])?><?php if($r['linked_missing_code']):?><br><b>Linked Missing Case:</b> <?=e($r['linked_missing_code'])?><?php endif;?><?php if($r['family_request_code']):?><br><b>Family Request:</b> <?=e($r['family_request_code'])?><?php endif;?><?php if($r['procedure_notes']):?><br><b>Procedure:</b> <?=nl2br(e($r['procedure_notes']))?><?php endif;?><br>Officer: <?=e($r['handover_officer_name'])?> · <?=e($r['handover_office'])?></p></div><?php endforeach;?><?php if(!$records):?><p class="muted">No handover recorded yet.</p><?php endif;?></div>
<?php page_footer(); ?>
