<?php
require_once __DIR__.'/../includes/layout.php'; require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/SimpleXlsx.php'; $admin=require_admin(['operator','approver','superadmin']); start_admin_session();
$expected=['type','name','age','gender','from_location','missing_person_context','associated_place_name','vehicle_no','nationality_code','nationality_name','identity_document_type','identity_document_number','last_contacted_bs','last_contacted_gregorian','last_seen_address','photo_file_name','family_contact_name','family_contact_phone','latitude','longitude','status','danger_level','rescue_description','additional_notes'];
function read_import_rows(string $path): array { $ext=strtolower(pathinfo($path,PATHINFO_EXTENSION)); if($ext==='csv'){ $h=fopen($path,'r');$rows=[];while(($r=fgetcsv($h))!==false)$rows[]=$r;fclose($h);return $rows;} return SimpleXlsx::read($path); }
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='upload'){
  try{if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Choose a CSV or XLSX file.');$ext=strtolower(pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['csv','xlsx'],true))throw new RuntimeException('Only CSV/XLSX supported.');$stored=date('YmdHis').'_'.random_token(5).'.'.$ext;$dest=app_config()['uploads']['import_dir'].'/'.$stored;if(!move_uploaded_file($_FILES['file']['tmp_name'],$dest))throw new RuntimeException('Could not store import file.');$rows=read_import_rows($dest);if(count($rows)<2)throw new RuntimeException('File must include header + at least one data row.');$stmt=db()->prepare('INSERT INTO imported_files(file_name,stored_name,uploaded_by_admin,status) VALUES (?,?,?,"preview")');$stmt->execute([$_FILES['file']['name'],$stored,$admin['id']]);$_SESSION['import_preview']=['batch_id'=>(int)db()->lastInsertId(),'stored'=>$stored,'headers'=>$rows[0],'sample'=>array_slice($rows,1,5)];audit($admin['id'],'import_upload',null,$_FILES['file']['name']);flash('success','File uploaded. Map the columns below.');}
  catch(Throwable $e){flash('danger',$e->getMessage());} redirect(base_url('admin/import.php'));
 }
 if($action==='commit' && !empty($_SESSION['import_preview'])){
  $p=$_SESSION['import_preview'];$path=app_config()['uploads']['import_dir'].'/'.$p['stored'];$rows=read_import_rows($path);$headers=array_shift($rows);$map=$_POST['map']??[];$errors=[];$count=0;db()->beginTransaction();
  try{foreach($rows as $ri=>$row){$d=[];foreach($map as $field=>$idx){if($idx!==''&&isset($row[(int)$idx]))$d[$field]=trim((string)$row[(int)$idx]);} $type=($d['type']??'missing')==='rescue_waiting'?'rescue_waiting':'missing';$name=$d['name']??($type==='rescue_waiting'?'Rescue Request':'');$phone=clean_phone($d['family_contact_phone']??'');if($type==='missing'&&$name===''){ $errors[]='Row '.($ri+2).': missing name';continue;}if(!valid_phone($phone)){ $errors[]='Row '.($ri+2).': invalid phone';continue;}if($type==='rescue_waiting'&&!valid_latlng($d['latitude']??null,$d['longitude']??null)){ $errors[]='Row '.($ri+2).': invalid rescue coordinates';continue;}
    $status=in_array($d['status']??'open',array_keys(case_status_labels()),true)?$d['status']:'open';$token=random_token(20);$stmt=db()->prepare('INSERT INTO cases(type,name,age,gender,from_location,missing_person_context,associated_place_name,purpose_en,purpose_np,vehicle_no,nationality_code,nationality_name,foreign_national_category,identity_document_type,identity_document_number,last_contacted_gregorian,last_contacted_bs,last_seen_address,family_contact_name,family_contact_phone,additional_notes,rescue_description,danger_level,status,public_token,created_by_admin_id,import_batch_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$type,$name,($d['age']??'')!==''?(int)$d['age']:null,in_array($d['gender']??'Unknown',['Male','Female','Other','Unknown'],true)?$d['gender']:'Unknown',$d['from_location']??'',($type==='missing'&&in_array($d['missing_person_context']??'',['local','worker','tourist','student','other'],true)?$d['missing_person_context']:null),($type==='missing'?($d['associated_place_name']??($d['purpose_np']??'')):null),($type==='missing'?($d['missing_person_context']??($d['purpose_en']??'')):($d['purpose_en']??'')),($type==='missing'?($d['associated_place_name']??($d['purpose_np']??'')):($d['purpose_np']??'')),$d['vehicle_no']??'',($type==='missing'?strtoupper($d['nationality_code']??'NP'):null),($type==='missing'?($d['nationality_name']??(($d['nationality_code']??'NP')==='NP'?'Nepal':'')):null),($type==='missing'?($d['foreign_national_category']??null):null),($type==='missing'?($d['identity_document_type']??null):null),($type==='missing'?($d['identity_document_number']??null):null),!empty($d['last_contacted_gregorian'])?date('Y-m-d H:i:s',strtotime($d['last_contacted_gregorian'])):null,$d['last_contacted_bs']??'',$d['last_seen_address']??'',$d['family_contact_name']??'Imported Contact',$phone,$d['additional_notes']??'',$d['rescue_description']??'',$d['danger_level']??null,$status,$token,$admin['id'],$p['batch_id']]);$id=(int)db()->lastInsertId();db()->prepare('UPDATE cases SET case_code=? WHERE id=?')->execute([case_code($id),$id]);if($type==='rescue_waiting')db()->prepare('INSERT INTO rescue_locations(case_id,latitude,longitude,address,timestamp_gregorian) VALUES (?,?,?,?,NOW())')->execute([$id,(float)$d['latitude'],(float)$d['longitude'],$d['last_seen_address']??'']);$count++;}
   db()->prepare("UPDATE imported_files SET status='imported',imported_count=?,error_report=? WHERE id=?")->execute([$count,$errors?implode("\n",$errors):null,$p['batch_id']]);db()->commit();audit($admin['id'],'import_commit',null,'Batch '.$p['batch_id'].': '.$count.' rows');unset($_SESSION['import_preview']);flash('success',"Imported $count rows. ".count($errors).' row(s) skipped.');}
   catch(Throwable $e){db()->rollBack();db()->prepare("UPDATE imported_files SET status='failed',error_report=? WHERE id=?")->execute([$e->getMessage(),$p['batch_id']]);flash('danger',$e->getMessage());}
   redirect(base_url('admin/import.php'));
 }
 if($action==='rollback'){ $bid=(int)($_POST['batch_id']??0);db()->prepare('UPDATE cases SET deleted_at=NOW(),deleted_by_admin_id=? WHERE import_batch_id=? AND deleted_at IS NULL')->execute([$admin['id'],$bid]);db()->prepare("UPDATE imported_files SET status='rolled_back' WHERE id=?")->execute([$bid]);audit($admin['id'],'import_rollback',null,'Batch '.$bid);flash('success','Import batch rolled back with soft delete.');redirect(base_url('admin/import.php')); }
}
$preview=$_SESSION['import_preview']??null;$history=db()->query('SELECT f.*,a.name admin_name FROM imported_files f LEFT JOIN admins a ON a.id=f.uploaded_by_admin ORDER BY f.id DESC LIMIT 50')->fetchAll();page_header('Import Excel',true);
?>
<div class="section-title"><h1>Excel / CSV Import</h1><div class="inline"><a class="btn btn-secondary" href="<?=e(base_url('samples/case_import_template.xlsx'))?>">Download Template</a><a class="btn btn-ghost" href="<?=e(base_url('admin/dashboard.php'))?>">Back</a></div></div>
<div class="card"><h2>1. Upload File</h2><form method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="action" value="upload"><label>CSV or XLSX<input type="file" name="file" accept=".csv,.xlsx" required></label><button class="btn btn-primary">Upload & Preview</button></form></div>
<?php if($preview):?><div class="card"><h2>2. Map Columns</h2><p class="muted">Map each database field to a source column. Required minimum: type, name (for missing), family_contact_phone; rescue rows also need latitude/longitude.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="commit"><div class="grid"><?php foreach($expected as $field):?><div class="col-4"><label><?=e($field)?><select name="map[<?=e($field)?>]"><option value="">-- Ignore --</option><?php foreach($preview['headers'] as $i=>$h):?><option value="<?=$i?>" <?=strtolower(trim((string)$h))===strtolower($field)?'selected':''?>><?=e($h)?></option><?php endforeach;?></select></label></div><?php endforeach;?></div><button class="btn btn-success" data-confirm="Import these rows now?">Import Valid Rows</button></form><h3 style="margin-top:24px">Preview</h3><div class="table-wrap"><table><thead><tr><?php foreach($preview['headers'] as $h):?><th><?=e($h)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($preview['sample'] as $r):?><tr><?php foreach($preview['headers'] as $i=>$h):?><td><?=e($r[$i]??'')?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<div class="card"><h2>Import History</h2><div class="table-wrap"><table><thead><tr><th>Batch</th><th>File</th><th>Admin</th><th>Status</th><th>Imported</th><th>Errors</th><th></th></tr></thead><tbody><?php foreach($history as $h):?><tr><td>#<?=e($h['id'])?><div class="small"><?=e($h['uploaded_at'])?></div></td><td><?=e($h['file_name'])?></td><td><?=e($h['admin_name'])?></td><td><?=e($h['status'])?></td><td><?=e($h['imported_count'])?></td><td><span class="small"><?=nl2br(e($h['error_report']))?></span></td><td><?php if($h['status']==='imported'):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="rollback"><input type="hidden" name="batch_id" value="<?=$h['id']?>"><button class="btn btn-sm btn-danger" data-confirm="Soft-delete all cases imported by this batch?">Rollback</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php page_footer(); ?>
