<?php
require_once __DIR__.'/../includes/layout.php';require_once __DIR__.'/../includes/auth.php';
$admin=require_admin();$id=(int)($_GET['id']??0);$q=db()->prepare('SELECT c.*,rd.identity_status rescued_identity,rd.rescue_location,rd.estimated_age_min r_age_min,rd.estimated_age_max r_age_max,rd.distinguishing_marks r_marks,dd.* FROM cases c LEFT JOIN rescued_person_details rd ON rd.case_id=c.id LEFT JOIN deceased_details dd ON dd.case_id=c.id WHERE c.id=? AND c.deleted_at IS NULL');$q->execute([$id]);$case=$q->fetch();if(!$case||!in_array($case['type'],['rescued','deceased'],true)){http_response_code(404);exit('Reconciliation is available for rescued/deceased records.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='run_match'&&can_manage_dvi($admin['role'])){$n=run_case_reconciliation($id,$admin['id']);audit($admin['id'],'run_reconciliation',$id,'Generated/updated '.$n.' candidates');flash('success','Reconciliation completed. '.$n.' candidate record(s) scored.');}
 elseif($action==='review_match'&&can_manage_dvi($admin['role'])){$mid=(int)($_POST['match_id']??0);$st=$_POST['match_status']??'reviewed';if(!in_array($st,['reviewed','rejected','confirmed'],true))$st='reviewed';$m=db()->prepare('SELECT * FROM case_matches WHERE id=? AND source_case_id=?');$m->execute([$mid,$id]);$match=$m->fetch();if($match){if($st==='confirmed'&&$case['type']==='deceased'){$st='reviewed';flash('warning','A deceased candidate link cannot be confirmed from similarity. Submit the separate identification approval request with competent forensic/official basis.');}db()->prepare('UPDATE case_matches SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?')->execute([$st,$admin['id'],$mid]);audit($admin['id'],'review_case_match',$id,'Match '.$mid.' => '.$st);}}
 elseif($action==='request_identification'&&$case['type']==='deceased'&&can_manage_dvi($admin['role'])){$missingId=(int)($_POST['missing_case_id']??0);$basis=trim((string)($_POST['identification_basis']??''));$ms=db()->prepare("SELECT * FROM cases WHERE id=? AND type='missing' AND deleted_at IS NULL");$ms->execute([$missingId]);$missing=$ms->fetch();if(!$missing)flash('danger','Select a valid missing-person candidate.');elseif($basis==='')flash('danger','Identification basis is required. State the fingerprint/DNA/dental or other competent official evidence.');else{$pending=db()->prepare("SELECT COUNT(*) FROM identification_approval_requests WHERE case_id=? AND status='pending'");$pending->execute([$id]);if((int)$pending->fetchColumn())flash('warning','An identification approval request is already pending.');else{db()->prepare("INSERT INTO identification_approval_requests(case_id,proposed_missing_case_id,proposed_identity_name,identification_basis,requested_by) VALUES (?,?,?,?,?)")->execute([$id,$missingId,$missing['name'],$basis,$admin['id']]);db()->prepare("UPDATE cases SET status='identification_review',status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$admin['id'],$id]);db()->prepare("UPDATE deceased_details SET identity_status='under_review' WHERE case_id=?")->execute([$id]);audit($admin['id'],'request_identification_approval',$id,$missing['case_code'].' | '.$basis);flash('success','Identification approval requested. A different Approver/Superadmin must review it.');}}}
 elseif($action==='review_identification'&&$case['type']==='deceased'&&can_approve_identification($admin['role'])){$rid=(int)($_POST['request_id']??0);$decision=$_POST['decision']??'';$notes=trim((string)($_POST['review_notes']??''));$r=db()->prepare("SELECT r.*,m.name missing_name,m.age missing_age,m.from_location missing_address FROM identification_approval_requests r LEFT JOIN cases m ON m.id=r.proposed_missing_case_id WHERE r.id=? AND r.case_id=? AND r.status='pending'");$r->execute([$rid,$id]);$req=$r->fetch();if(!$req)flash('danger','Pending identification request not found.');elseif((int)$req['requested_by']===(int)$admin['id'])flash('danger','Separation of duties: the person who requested identification cannot approve the same request.');elseif(!in_array($decision,['approved','rejected'],true))flash('danger','Choose approve or reject.');else{db()->beginTransaction();try{db()->prepare('UPDATE identification_approval_requests SET status=?,reviewed_by=?,reviewed_at=NOW(),review_notes=? WHERE id=?')->execute([$decision,$admin['id'],$notes,$rid]);if($decision==='approved'){$basis=$req['identification_basis'];db()->prepare("UPDATE deceased_details SET identity_status='confirmed',official_identification_method=?,official_identity_name=?,official_identity_age=?,official_identity_address=?,identification_approved_by=?,identification_approved_at=NOW() WHERE case_id=?")->execute([$basis,$req['missing_name'],$req['missing_age'],$req['missing_address'],$admin['id'],$id]);db()->prepare("UPDATE cases SET name=?,age=?,from_location=?,status='forensic_confirmed',status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$req['missing_name'],$req['missing_age'],$req['missing_address'],$admin['id'],$id]);db()->prepare("UPDATE case_matches SET status='confirmed',reviewed_by=?,reviewed_at=NOW() WHERE source_case_id=? AND candidate_case_id=?")->execute([$admin['id'],$id,$req['proposed_missing_case_id']]);db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,condition_after,note,public_visible) VALUES (?,?,'status','forensic_confirmed','deceased','Identity formally approved. Public identity remains restricted unless separately released.',1)")->execute([$id,$admin['id']]);}else{db()->prepare("UPDATE deceased_details SET identity_status='unidentified' WHERE case_id=?")->execute([$id]);db()->prepare("UPDATE cases SET status='under_review',status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$admin['id'],$id]);}db()->commit();audit($admin['id'],'review_identification',$id,$decision.' | '.$notes);flash('success','Identification review saved: '.$decision);}catch(Throwable $e){db()->rollBack();flash('danger',$e->getMessage());}}}
 elseif($action==='release_identity'&&$case['type']==='deceased'&&can_approve_identification($admin['role'])){$v=!empty($_POST['public_identity_release'])?1:0;db()->prepare('UPDATE deceased_details SET public_identity_release=? WHERE case_id=?')->execute([$v,$id]);audit($admin['id'],'set_public_identity_release',$id,$v?'released':'restricted');flash('success',$v?'Official identity may now appear in public search.':'Official identity is restricted from public search.');}
 redirect(base_url('admin/reconciliation.php?id='.$id));
}
$ms=db()->prepare('SELECT cm.*,m.case_code candidate_code,m.name candidate_name,m.age candidate_age,m.gender candidate_gender,m.from_location,m.last_seen_address,m.last_contacted_bs,m.photo_url,a.name reviewed_name FROM case_matches cm JOIN cases m ON m.id=cm.candidate_case_id LEFT JOIN admins a ON a.id=cm.reviewed_by WHERE cm.source_case_id=? ORDER BY cm.match_score DESC,cm.id DESC');$ms->execute([$id]);$matches=$ms->fetchAll();
$fr=db()->prepare('SELECT * FROM family_match_requests WHERE target_case_id=? ORDER BY created_at DESC');$fr->execute([$id]);$familyRequests=$fr->fetchAll();
$ia=db()->prepare('SELECT r.*,rq.name requested_name,rv.name reviewed_name,m.case_code missing_code FROM identification_approval_requests r JOIN admins rq ON rq.id=r.requested_by LEFT JOIN admins rv ON rv.id=r.reviewed_by LEFT JOIN cases m ON m.id=r.proposed_missing_case_id WHERE r.case_id=? ORDER BY r.id DESC');$ia->execute([$id]);$identReqs=$ia->fetchAll();
page_header('Reconciliation',true);
?>
<div class="section-title"><div><div class="card-kicker">MATCHING & VERIFICATION</div><h1><?=e($case['case_code'])?> · <?=e(case_type_label($case['type']))?></h1><div class="muted">Candidate similarity is a search aid. It does not itself establish identity.</div></div><div class="inline"><a class="btn btn-secondary" href="<?=e(base_url('admin/case.php?id='.$id))?>">Open Case</a><a class="btn btn-ghost" href="<?=e(base_url('admin/dashboard.php'))?>">Cases</a></div></div>
<div class="reconcile-summary-grid"><div class="state-card"><span>Status</span><strong><?=e(case_status_label($case['status']))?></strong></div><div class="state-card"><span>Person / Body</span><strong><?=e($case['name'])?></strong></div><div class="state-card"><span>Gender</span><strong><?=e($case['gender'])?></strong></div><div class="state-card"><span>Location</span><strong><?=e($case['type']==='deceased'?($case['recovery_location']??''):($case['rescue_location']??''))?></strong></div></div>
<div class="card"><div class="section-title compact-title"><div><h2>Potential Missing-Person Matches</h2><div class="muted small">Weighted by name, age, gender and location. No photo/face match is used by this engine.</div></div><?php if(can_manage_dvi($admin['role'])):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="run_match"><button class="btn btn-primary">Run / Refresh Matching</button></form><?php endif;?></div>
<div class="table-wrap"><table><thead><tr><th>Score</th><th>Missing Case</th><th>Person</th><th>Last Seen</th><th>Reasons</th><th>Review</th></tr></thead><tbody><?php foreach($matches as $m):?><tr><td><strong><?=e(number_format((float)$m['match_score'],0))?>%</strong></td><td><?=e($m['candidate_code'])?></td><td><b><?=e($m['candidate_name'])?></b><br><span class="small">Age <?=e($m['candidate_age']??'?')?> · <?=e($m['candidate_gender'])?></span></td><td><?=e($m['last_seen_address']?:$m['from_location'])?><br><span class="small"><?=e($m['last_contacted_bs'])?></span></td><td><?php foreach(json_decode($m['reasons_json']??'[]',true)?:[] as $reason):?><span class="match-reason"><?=e($reason)?></span><?php endforeach;?></td><td><span class="status"><?=e($m['status'])?></span><?php if(can_manage_dvi($admin['role'])):?><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="review_match"><input type="hidden" name="match_id" value="<?=$m['id']?>"><select name="match_status"><option value="reviewed">Reviewed</option><option value="rejected">Reject</option><?php if($case['type']==='rescued'):?><option value="confirmed">Confirm candidate link</option><?php endif;?></select><button class="btn btn-sm btn-secondary">Save</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$matches):?><tr><td colspan="6">No candidate scores yet. Run matching.</td></tr><?php endif;?></tbody></table></div></div>

<?php if($case['type']==='deceased'):?>
<div class="card dvi-approval-card"><h2>Formal Identification Approval</h2><div class="alert alert-warning"><b>Do not approve from score, clothing or visual recognition alone.</b> Record the competent forensic/official basis such as fingerprint, DNA or dental evidence.</div>
<?php if(can_manage_dvi($admin['role'])):?><form method="post" class="grid"><?=csrf_field()?><input type="hidden" name="action" value="request_identification"><div class="col-4"><label>Proposed Missing Person<select name="missing_case_id" required><option value="">Select candidate</option><?php foreach($matches as $m):if($m['status']==='rejected')continue;?><option value="<?=$m['candidate_case_id']?>"><?=e($m['candidate_code'].' · '.$m['candidate_name'].' · '.$m['match_score'].'%')?></option><?php endforeach;?></select></label></div><div class="col-8"><label>Identification Basis *<textarea name="identification_basis" required placeholder="Example: Fingerprint reference ... confirmed by ...; DNA laboratory reference ..."></textarea></label></div><div class="col-12"><button class="btn btn-primary">Submit Identification Approval Request</button></div></form><?php endif;?>
<?php foreach($identReqs as $r):?><div class="approval-request <?=e($r['status'])?>"><div><b><?=e($r['proposed_identity_name'])?></b> · <?=e($r['missing_code'])?> <span class="status"><?=e($r['status'])?></span><p><?=nl2br(e($r['identification_basis']))?></p><span class="small">Requested by <?=e($r['requested_name'])?> · <?=e($r['requested_at'])?></span></div><?php if($r['status']==='pending'&&can_approve_identification($admin['role'])):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="review_identification"><input type="hidden" name="request_id" value="<?=$r['id']?>"><label>Review notes<textarea name="review_notes"></textarea></label><div class="inline"><button class="btn btn-success" name="decision" value="approved" data-confirm="Approve this formal identification?">Approve Identification</button><button class="btn btn-danger" name="decision" value="rejected">Reject</button></div></form><?php endif;?></div><?php endforeach;?>
<?php if(($case['identity_status']??'')==='confirmed'&&can_approve_identification($admin['role'])):?><form method="post" class="release-form"><?=csrf_field()?><input type="hidden" name="action" value="release_identity"><label class="check-label"><input type="checkbox" name="public_identity_release" value="1" <?=!empty($case['public_identity_release'])?'checked':''?>><span><b>Allow officially confirmed identity to appear in public search</b><small>Keep off until the competent authority has authorized public release.</small></span></label><button class="btn btn-secondary">Save Public Release Setting</button></form><?php endif;?></div>
<?php endif;?>

<div class="card"><div class="section-title compact-title"><div><h2>Family Match Requests</h2><div class="muted small">Public users who selected “This may be my family member”.</div></div><a class="btn btn-secondary" href="<?=e(base_url('admin/family_requests.php'))?>">Open All Requests</a></div><?php foreach($familyRequests as $r):?><div class="family-request-row"><div><b><?=e($r['request_code'])?> · <?=e($r['missing_person_name'])?></b><span class="small"><?=e($r['requester_name'])?> · <?=e($r['relationship'])?> · <?=e($r['requester_phone'])?></span></div><span class="status"><?=e($r['status'])?><?=empty($r['phone_verified'])?' · phone unverified':''?></span></div><?php endforeach;?><?php if(!$familyRequests):?><p class="muted">No public family match request is linked to this record.</p><?php endif;?></div>
<?php page_footer(); ?>
