<?php
require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/SimpleXlsx.php';
header('Content-Type: application/json; charset=utf-8');
function j($data,int $status=200): never { http_response_code($status); echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function json_input(): array { $raw=file_get_contents('php://input'); $d=json_decode($raw,true); return is_array($d)?$d:[]; }
function api_admin(array $roles=null): array { $a=current_admin(); if(!$a)j(['error'=>'Authentication required'],401); if($roles&&!in_array($a['role'],$roles,true))j(['error'=>'Permission denied'],403); return $a; }
$route=trim($_GET['route']??'','/'); $method=$_SERVER['REQUEST_METHOD'];
try {
 if($route==='auth/login' && $method==='POST'){ $d=$_POST?:json_input(); if(login_admin(trim($d['login']??$d['email']??''),$d['password']??'')) j(['ok'=>true,'admin'=>current_admin()]); j(['error'=>'Invalid credentials'],401); }
 if($route==='auth/logout' && $method==='POST'){ api_admin(); logout_admin(); j(['ok'=>true]); }
 if($route==='cases/import' && $method==='POST'){
   $a=api_admin(['operator','approver','superadmin']); if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)j(['error'=>'CSV/XLSX file required'],422); $ext=strtolower(pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION)); if(!in_array($ext,['csv','xlsx'],true))j(['error'=>'Only CSV/XLSX supported'],422);
   $stored=date('YmdHis').'_'.random_token(5).'.'.$ext; $dest=app_config()['uploads']['import_dir'].'/'.$stored; if(!move_uploaded_file($_FILES['file']['tmp_name'],$dest))j(['error'=>'Could not store upload'],500);
   if($ext==='csv'){ $h=fopen($dest,'r');$rows=[];while(($r=fgetcsv($h))!==false)$rows[]=$r;fclose($h);} else {$rows=SimpleXlsx::read($dest);} if(count($rows)<2)j(['error'=>'Header + data rows required'],422); $headers=array_map(fn($v)=>strtolower(trim((string)$v)),array_shift($rows));
   $stmt=db()->prepare("INSERT INTO imported_files(file_name,stored_name,uploaded_by_admin,status) VALUES (?,?,?,'preview')");$stmt->execute([$_FILES['file']['name'],$stored,$a['id']]);$batch=(int)db()->lastInsertId(); $count=0;$errors=[]; db()->beginTransaction();
   try{foreach($rows as $ri=>$row){$d=[];foreach($headers as $i=>$hname)if($hname!==''&&isset($row[$i]))$d[$hname]=trim((string)$row[$i]);$type=($d['type']??$d['case_type']??'missing')==='rescue_waiting'?'rescue_waiting':'missing';$name=$d['name']??($type==='rescue_waiting'?'Rescue Request':'');$phone=clean_phone($d['family_contact_phone']??'');if($type==='missing'&&$name===''){ $errors[]='Row '.($ri+2).': missing name';continue;}if(!valid_phone($phone)){ $errors[]='Row '.($ri+2).': invalid phone';continue;}if($type==='rescue_waiting'&&!valid_latlng($d['latitude']??null,$d['longitude']??null)){ $errors[]='Row '.($ri+2).': invalid coordinates';continue;} $status=in_array($d['status']??'open',array_keys(case_status_labels()),true)?$d['status']:'open';$token=random_token(20);
     $ins=db()->prepare('INSERT INTO cases(type,name,age,gender,from_location,missing_person_context,associated_place_name,purpose_en,purpose_np,vehicle_no,last_contacted_gregorian,last_contacted_bs,last_seen_address,family_contact_name,family_contact_phone,additional_notes,rescue_description,danger_level,status,public_token,created_by_admin_id,import_batch_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$ins->execute([$type,$name,($d['age']??'')!==''?(int)$d['age']:null,in_array($d['gender']??'Unknown',['Male','Female','Other','Unknown'],true)?$d['gender']:'Unknown',$d['from_location']??$d['from']??'',($type==='missing'?($d['missing_person_context']??null):null),($type==='missing'?($d['associated_place_name']??null):null),$d['purpose_en']??($d['missing_person_context']??''),$d['purpose_np']??($d['associated_place_name']??''),$d['vehicle_no']??'',!empty($d['last_contacted_gregorian'])?date('Y-m-d H:i:s',strtotime($d['last_contacted_gregorian'])):null,$d['last_contacted_bs']??'',$d['last_seen_address']??'',$d['family_contact_name']??'Imported Contact',$phone,$d['additional_notes']??'',$d['rescue_description']??'',$d['danger_level']??null,$status,$token,$a['id'],$batch]);$id=(int)db()->lastInsertId();db()->prepare('UPDATE cases SET case_code=? WHERE id=?')->execute([case_code($id),$id]);if($type==='rescue_waiting')db()->prepare('INSERT INTO rescue_locations(case_id,latitude,longitude,address,timestamp_gregorian) VALUES (?,?,?,?,NOW())')->execute([$id,(float)$d['latitude'],(float)$d['longitude'],$d['last_seen_address']??'']);$count++;}
     db()->prepare("UPDATE imported_files SET status='imported',imported_count=?,error_report=? WHERE id=?")->execute([$count,$errors?implode("\n",$errors):null,$batch]);db()->commit();audit($a['id'],'api_import',null,'Batch '.$batch.' imported '.$count);j(['batch_id'=>$batch,'imported'=>$count,'errors'=>$errors],201);
   }catch(Throwable $e){db()->rollBack();db()->prepare("UPDATE imported_files SET status='failed',error_report=? WHERE id=?")->execute([$e->getMessage(),$batch]);throw $e;}
 }
 if($route==='cases' && $method==='POST'){
   public_rate_limit(); $d=$_POST?:json_input(); $type=($d['type']??'missing')==='rescue_waiting'?'rescue_waiting':'missing';$phone=clean_phone($d['family_contact_phone']??'');
   if(!valid_phone($phone))j(['error'=>'Valid family_contact_phone required'],422); if($type==='missing'&&trim($d['name']??'')==='')j(['error'=>'name required'],422); if($type==='rescue_waiting'&&!valid_latlng($d['latitude']??null,$d['longitude']??null))j(['error'=>'latitude/longitude required'],422);
   $photo=null;if(!empty($_FILES['photo']))$photo=save_uploaded_photo($_FILES['photo']);$token=random_token(20);$status=($d['status']??'open')==='draft'?'draft':'open';
   $stmt=db()->prepare('INSERT INTO cases(type,name,age,gender,from_location,missing_person_context,associated_place_name,purpose_en,purpose_np,vehicle_no,last_contacted_gregorian,last_contacted_bs,last_seen_address,photo_url,thumb_url,family_contact_name,family_contact_phone,additional_notes,rescue_description,danger_level,needs_rescue,status,public_token) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
   $stmt->execute([$type,trim($d['name']??($type==='rescue_waiting'?'Rescue Request':'')),isset($d['age'])?(int)$d['age']:null,$d['gender']??'Unknown',$d['from_location']??'',($type==='missing'?($d['missing_person_context']??null):null),($type==='missing'?($d['associated_place_name']??null):null),$d['purpose_en']??($d['missing_person_context']??''),$d['purpose_np']??($d['associated_place_name']??''),$d['vehicle_no']??'',!empty($d['last_contacted_gregorian'])?date('Y-m-d H:i:s',strtotime($d['last_contacted_gregorian'])):null,$d['last_contacted_bs']??'',$d['last_seen_address']??($d['address']??''),$photo['photo']??null,$photo['thumb']??null,$d['family_contact_name']??'',$phone,$d['additional_notes']??'',$d['rescue_description']??'',$d['danger_level']??null,!empty($d['needs_rescue'])?1:0,$status,$token]);$id=(int)db()->lastInsertId();$code=case_code($id);db()->prepare('UPDATE cases SET case_code=? WHERE id=?')->execute([$code,$id]);
   if($type==='rescue_waiting')db()->prepare('INSERT INTO rescue_locations(case_id,latitude,longitude,address,accuracy,timestamp_gregorian,timestamp_bs) VALUES (?,?,?,?,?,NOW(),?)')->execute([$id,(float)$d['latitude'],(float)$d['longitude'],$d['address']??'',$d['accuracy']??null,$d['timestamp_bs']??'']); log_public_submission(); j(['case_id'=>$id,'case_code'=>$code,'public_token'=>$token,'timestamp'=>now_sql()],201);
 }
 if($route==='cases' && $method==='GET'){
   api_admin();$where=['deleted_at IS NULL'];$args=[];foreach(['status','type'] as $f)if(!empty($_GET[$f])){$where[]="$f=?";$args[]=$_GET[$f];}if(!empty($_GET['q'])){$where[]='(case_code LIKE ? OR name LIKE ? OR family_contact_phone LIKE ? OR last_seen_address LIKE ?)';for($i=0;$i<4;$i++)$args[]='%'.$_GET['q'].'%';}$page=max(1,(int)($_GET['page']??1));$per=min(100,max(1,(int)($_GET['per_page']??30)));$off=($page-1)*$per;$stmt=db()->prepare('SELECT * FROM cases WHERE '.implode(' AND ',$where).' ORDER BY id DESC LIMIT '.$per.' OFFSET '.$off);$stmt->execute($args);j(['data'=>$stmt->fetchAll(),'page'=>$page,'per_page'=>$per]);
 }

 if(preg_match('#^cases/(\d+)/updates$#',$route,$m)){
   $a=api_admin();$id=(int)$m[1];
   if($method==='GET'){$st=db()->prepare('SELECT u.*,a.name admin_name,a.office_name FROM case_updates u LEFT JOIN admins a ON a.id=u.admin_id WHERE u.case_id=? ORDER BY u.created_at DESC,u.id DESC');$st->execute([$id]);j(['data'=>$st->fetchAll()]);}
   if($method==='POST'){
     if(!in_array($a['role'],['operator','approver','superadmin'],true))j(['error'=>'Permission denied'],403);$d=$_POST?:json_input();
     $cs=db()->prepare('SELECT * FROM cases WHERE id=? AND deleted_at IS NULL');$cs->execute([$id]);$c=$cs->fetch();if(!$c)j(['error'=>'Not found'],404);
     $allowed=match($c['type']){'missing'=>['open','under_review','searching','located','found_alive','found_injured','found_deceased','shifted'],'rescue_waiting'=>['open','under_review','rescue_dispatched','located','rescued_safe','rescued_injured','found_deceased','shifted'],'rescued'=>['open','under_review','identity_unknown','potential_match','family_contacted','rescued_safe','rescued_injured','shifted'],'deceased'=>['identity_unknown','potential_match','family_contacted','identification_review','shifted'],default=>['open']};
     $status=(string)($d['status']??'');if(!in_array($status,$allowed,true))j(['error'=>'Invalid status for case type'],422);
     $condition=(string)($d['condition']??'unknown');if(!array_key_exists($condition,case_condition_labels()))$condition='unknown';$infer=['found_alive'=>'alive','found_injured'=>'injured','found_deceased'=>'deceased','rescued_safe'=>'safe','rescued_injured'=>'injured'];if($condition==='unknown'&&isset($infer[$status]))$condition=$infer[$status];
     $wf=trim((string)($d['where_found']??''));$cl=trim((string)($d['current_location']??''));$stTo=trim((string)($d['shifted_to']??''));$note=trim((string)($d['note']??''));$lat=$d['latitude']??null;$lng=$d['longitude']??null;if(($lat!==null||$lng!==null)&&!valid_latlng($lat,$lng))j(['error'=>'Invalid coordinates'],422);$public=array_key_exists('public_visible',$d)?(int)(bool)$d['public_visible']:1;
     $cat=str_starts_with($status,'found_')||$status==='located'?'found':(str_starts_with($status,'rescue_')||str_starts_with($status,'rescued_')?'rescue':($status==='shifted'?'transfer':($status==='searching'?'search':'status')));
     db()->beginTransaction();try{db()->prepare('INSERT INTO case_updates(case_id,admin_id,update_category,status_after,condition_after,where_found,current_location,shifted_to,latitude,longitude,note,public_visible) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$a['id'],$cat,$status,$condition,$wf?:null,$cl?:null,$stTo?:null,$lat,$lng,$note?:null,$public]);db()->prepare("UPDATE cases SET status=?,current_condition=?,current_location=COALESCE(NULLIF(?,''),current_location),where_found=COALESCE(NULLIF(?,''),where_found),shifted_to=COALESCE(NULLIF(?,''),shifted_to),status_note=COALESCE(NULLIF(?,''),status_note),status_updated_at=NOW(),status_updated_by=?,updated_at=NOW() WHERE id=?")->execute([$status,$condition,$cl,$wf,$stTo,$note,$a['id'],$id]);db()->commit();audit($a['id'],'api_case_progress_update',$id,$status);j(['ok'=>true,'status'=>$status],201);}catch(Throwable $e){db()->rollBack();throw $e;}
   }
 }
 if(preg_match('#^cases/(\d+)$#',$route,$m)){
   $a=api_admin();$id=(int)$m[1]; if($method==='GET'){$stmt=db()->prepare('SELECT c.*,r.latitude,r.longitude,r.accuracy,r.address rescue_address FROM cases c LEFT JOIN rescue_locations r ON r.id=(SELECT MAX(r2.id) FROM rescue_locations r2 WHERE r2.case_id=c.id) WHERE c.id=? AND c.deleted_at IS NULL');$stmt->execute([$id]);$c=$stmt->fetch();if(!$c)j(['error'=>'Not found'],404);j($c);}
   if($method==='PUT'){if(!in_array($a['role'],['operator','approver','superadmin'],true))j(['error'=>'Permission denied'],403);$d=json_input();$allowed=['name','age','gender','from_location','missing_person_context','associated_place_name','purpose_en','purpose_np','vehicle_no','last_contacted_gregorian','last_contacted_bs','last_seen_address','family_contact_name','family_contact_phone','additional_notes','rescue_description','danger_level'];$sets=[];$args=[];foreach($allowed as $f)if(array_key_exists($f,$d)){$sets[]="$f=?";$args[]=$f==='family_contact_phone'?clean_phone((string)$d[$f]):$d[$f];}if(!$sets)j(['error'=>'No fields to update'],422);$args[]=$id;db()->prepare('UPDATE cases SET '.implode(',',$sets).',updated_at=NOW() WHERE id=?')->execute($args);audit($a['id'],'api_update',$id,json_encode(array_keys($d)));j(['ok'=>true]);}
 }
 if(preg_match('#^cases/(\d+)/close$#',$route,$m) && $method==='POST'){$a=api_admin(['operator','approver','superadmin']);$id=(int)$m[1];$d=$_POST?:json_input();$reason=trim($d['reason']??'');if(!$reason)j(['error'=>'reason required'],422);if(can_close($a['role'])){db()->prepare("UPDATE cases SET status='closed',close_reason=?,closed_at=NOW(),closed_by_admin_id=?,status_updated_at=NOW(),status_updated_by=? WHERE id=?")->execute([$reason,$a['id'],$a['id'],$id]);db()->prepare("INSERT INTO case_updates(case_id,admin_id,update_category,status_after,note,public_visible) VALUES (?,?,'status','closed','Case formally closed.',1)")->execute([$id,$a['id']]);audit($a['id'],'api_close',$id,$reason);j(['ok'=>true,'status'=>'closed']);}db()->prepare('INSERT INTO close_approval_requests(case_id,requested_by,reason) VALUES (?,?,?)')->execute([$id,$a['id'],$reason]);audit($a['id'],'api_request_close',$id,$reason);j(['ok'=>true,'status'=>'approval_pending']);}
 if($route==='admins' && $method==='GET'){api_admin(['approver','superadmin']);$rows=db()->query('SELECT id,name,phone,email,post_title,office_name,role,is_active,created_at FROM admins ORDER BY id DESC')->fetchAll();j($rows);}
 if($route==='admins' && $method==='POST'){$a=api_admin(['approver','superadmin']);$d=$_POST?:json_input();$role=$d['role']??'viewer';if(!in_array($role,['viewer','operator','approver','superadmin'],true))j(['error'=>'Invalid role'],422);if($role==='superadmin' && $a['role']!=='superadmin')j(['error'=>'Only superadmin can create another superadmin'],403);$stmt=db()->prepare('INSERT INTO admins(name,phone,email,post_title,office_name,password_hash,role) VALUES (?,?,?,?,?,?,?)');$stmt->execute([$d['name']??'',clean_phone($d['phone']??''),$d['email']??'',$d['post_title']??'',$d['office_name']??'',password_hash($d['password']??random_token(10),PASSWORD_DEFAULT),$role]);audit($a['id'],'api_create_admin');j(['id'=>(int)db()->lastInsertId()],201);}
 if($route==='export/xlsx' && $method==='GET'){api_admin();header_remove('Content-Type');$qs=isset($_GET['ids'])?'?ids='.urlencode($_GET['ids']):'';redirect(base_url('admin/export.php'.$qs));}
 if(preg_match('#^cases/(\d+)/(pdf|idcard)$#',$route,$m) && $method==='GET'){api_admin();header_remove('Content-Type');redirect(base_url('admin/'.($m[2]==='pdf'?'report.php':'idcard.php').'?id='.$m[1]));}
 j(['error'=>'Endpoint not found','route'=>$route],404);
} catch(Throwable $e){j(['error'=>'Server error','message'=>$e->getMessage()],500);}
